
// Generated by AlexConf: do not edit
#include "AConf.hh"
using namespace alex ;
AAConf::AAConf()
{
  fAlgoPathName.first="/Users/jjgomezcadenas/Development/devnext/alex2/jjalgos";
  fAlgoPathName.second="AlgoConfig.xml";
  fDstPathName.first="/Users/jjgomezcadenas/Development/NEXT/DATA";
  fDstPathName.second="MagBox_Xe_10atm_00tesla.Xe136_bb0nu.next";
  fHistoPathName.first="/Users/jjgomezcadenas/Development/devnext/alex-build/alexMain";
  fHistoPathName.second="MagBox_Xe_10atm_00tesla.Xe136_bb0nu.histos.root";
  fEvents.first=10000;
  fEvents.second=10;
  fDebug="DEBUG";
}
