
#ifndef ALGOKalmanSetup_
#define ALGOKalmanSetup_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
namespace alex {
  class KalmanSetup: public IAlgorithm {
  public:
    KalmanSetup();
    ~KalmanSetup(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
    std::string  Name() const {return fName;}
    void SetName(std::string name) {fName = name;}
  private:
    std::string fName;
    std::string gas;
    std::string model;
    double Pr;
    double B;
    double maxChi2;
    double maxOutliers;
    double maxExtrapFailures;
    double minDistanceNodeOrdering;
    double minGoodNodeOrdering;
    std::string fitterVerbosity;
    std::string navigationVerbosity;
    std::string modelVerbosity;
    std::string matchingVerbosity;
  };
}
#endif 
