
#ifndef ALGONConstructRBetas_
#define ALGONConstructRBetas_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
namespace alex {
  class NConstructRBetas: public IAlgorithm {
  public:
    NConstructRBetas();
    ~NConstructRBetas(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
    std::string  Name() const {return fName;}
    void SetName(std::string name) {fName = name;}
  private:
    std::string fName;
    double fCoreDist;
    int fSparseWidth;
    double fBlobRadius;
    TH1F* fH1_nIBetas;
  };
}
#endif 
