
#ifndef ALGONDrawEffHits_
#define ALGONDrawEffHits_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
namespace alex {
  class NDrawEffHits: public IAlgorithm {
  public:
    NDrawEffHits();
    ~NDrawEffHits(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
    std::string  Name() const {return fName;}
    void SetName(std::string name) {fName = name;}
  private:
    std::string fName;
    int fDraw;
  };
}
#endif 
