
#ifndef ALGONSelectIBetas_
#define ALGONSelectIBetas_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
namespace alex {
  class NSelectIBetas: public IAlgorithm {
  public:
    NSelectIBetas();
    ~NSelectIBetas(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
    std::string  Name() const {return fName;}
    void SetName(std::string name) {fName = name;}
  private:
    std::string fName;
    int fSelect;
    int fMaxIBetas;
  };
}
#endif 
