
#ifndef ALGOAEx1_
#define ALGOAEx1_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
namespace alex {
  class AEx1: public IAlgorithm {
  public:
    AEx1();
    ~AEx1(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
    std::string  Name() const {return fName;}
    void SetName(std::string name) {fName = name;}
  private:
    std::string fName;
    TH1F* fH1_X;
    TH2F* fH2_XY;
  };
}
#endif 
