
// Generated by AlexConf: do not edit
#include <AAConf.h>
AAConf::AAConf()
{
  fAlgoPathName.first=/Users/jjgomezcadenas/Development/devnext/alex2/example
  fAlgoPathName.second=AlgoConfig.xml
  fDstPathName.first=/Users/jjgomezcadenas/Development/NEXT/DATA
  fDstPathName.second=basic.dat
  fHistoPathName.first=/Users/jjgomezcadenas/Development/devnext/alex-build/test
  fHistoPathName.second=exHistos.root
  fEvents.first=1000
  fEvents.second=10
  fDebug=DEBUG
}
