# Try to find TINYXML2
#
#


SET(TINYXML2_CONFIG_PATH 
  $ENV{TINYXML2_DIR}/bin
) 
 
FIND_PROGRAM(TINYXML2_CONFIG tinyxml2-config
  ${TINYXML2_CONFIG_PATH}
)

MESSAGE("DBG TINYXML2_CONFIG ${TINYXML2_CONFIG}")
   
IF (TINYXML2_CONFIG) 

  EXEC_PROGRAM(${TINYXML2_CONFIG}
        ARGS --prefix
        OUTPUT_VARIABLE TINYXML2_PREFIX)

  MESSAGE("DBG TINYXML2_PREFIX ${TINYXML2_PREFIX}")
  SET(TINYXML2_INCLUDE_DIR ${TINYXML2_PREFIX}/include CACHE STRING INTERNAL)
  MESSAGE("DBG TINYXML2_INCLUDE_DIR ${TINYXML2_INCLUDE_DIR}")
  SET(TINYXML2_LIBRARY_DIR ${TINYXML2_PREFIX}/lib CACHE STRING INTERNAL)
  MESSAGE("DBG TINYXML2_LIBRARY_DIR ${TINYXML2_LIBRARY_DIR}")

 
  EXEC_PROGRAM( ${TINYXML2_CONFIG}
    ARGS "--libs" 
    OUTPUT_VARIABLE TINYXML2_flags )

  SET(TINYXML2_LIBRARIES ${TINYXML2_flags})

  MESSAGE("DBG TINYXML2_LIBRARIES ${TINYXML2_LIBRARIES}")


  SET(LD_LIBRARY_PATH ${LD_LIBRARY_PATH} ${TINYXML2_LIBRARY_DIR})

  MESSAGE("LD_LIBRARY_PATH ${LD_LIBRARY_PATH}")

  
    ELSE(TINYXML2_CONFIG)
      MESSAGE("FindTINYXML2.cmake: TINYXML2-config not found. Please set it manually. TINYXML2_CONFIG=${TINYXML2_CONFIG}")
    ENDIF(TINYXML2_CONFIG)

IF(TINYXML2_LIBRARIES)
  IF(TINYXML2_INCLUDE_DIR OR TINYXML2_CXX_FLAGS)

    SET(TINYXML2_FOUND 1)
    
  ENDIF(TINYXML2_INCLUDE_DIR OR TINYXML2_CXX_FLAGS)
ENDIF(TINYXML2_LIBRARIES)

