# Try to find RECPACK
#
# --------------------------------


SET(RECPACK_CONFIG_PATH 
  $ENV{RECPACK_DIR}/bin
) 
 
FIND_PROGRAM(RECPACK_CONFIG recpack-config
  ${RECPACK_CONFIG_PATH}
)

MESSAGE("DBG RECPACK_CONFIG ${RECPACK_CONFIG}")
   
IF (RECPACK_CONFIG) 
      
    EXEC_PROGRAM(${RECPACK_CONFIG}
        ARGS --prefix
        OUTPUT_VARIABLE RECPACK_PREFIX)

    MESSAGE("DBG RECPACK_PREFIX ${RECPACK_PREFIX}")

    SET(RECPACK_INCLUDES_DIR ${RECPACK_PREFIX}/include CACHE STRING INTERNAL)
    MESSAGE("DBG RECPACK_INCLUDES_DIR ${RECPACK_INCLUDES_DIR}")

    SET(RECPACK_LIBRARY_DIR ${RECPACK_PREFIX}/lib CACHE STRING INTERNAL)
    MESSAGE("DBG RECPACK_LIBRARY_DIR ${RECPACK_LIBRARY_DIR}")
      
    # ask RECPACK-config for the library varaibles
    EXEC_PROGRAM( ${RECPACK_CONFIG}
    ARGS "--libs" 
    OUTPUT_VARIABLE RECPACK_flags )

    SET(RECPACK_LIBRARIES ${RECPACK_flags})

    MESSAGE("DBG RECPACK_LIBRARIES ${RECPACK_LIBRARIES}")

    SET(LD_LIBRARY_PATH ${LD_LIBRARY_PATH} ${RECPACK_LIBRARY_DIR})
    MESSAGE("LD_LIBRARY_PATH ${LD_LIBRARY_PATH}")

  
      
  ELSE(RECPACK_CONFIG)
    MESSAGE("FindRECPACK.cmake: RECPACK-config not found. Please set it manually. RECPACK_CONFIG=${RECPACK_CONFIG}")
  ENDIF(RECPACK_CONFIG)

IF(RECPACK_LIBRARIES)
  IF(RECPACK_INCLUDES_DIR)

    SET(RECPACK_FOUND 1)
    
  ENDIF(RECPACK_INCLUDES_DIR)
ENDIF(RECPACK_LIBRARIES)

