# Try to find PAOLINA
#
# 


SET(PAOLINA_CONFIG_PATH 
  $ENV{PAOLINA}/bin
) 
 
FIND_PROGRAM(PAOLINA_CONFIG paolina-config
  ${PAOLINA_CONFIG_PATH}
)

MESSAGE("DBG PAOLINA_CONFIG ${PAOLINA_CONFIG}")
   
IF (PAOLINA_CONFIG) 

  # ask PAOLINA-config for the library dir
  # Set PAOLINA_LIBRARY_DIR

  EXEC_PROGRAM( ${PAOLINA_CONFIG}
    ARGS "--libdir"
    OUTPUT_VARIABLE PAOLINA_LIBRARY_DIR)
    
  MESSAGE("DBG PAOLINA_LIBRARY_DIR ${PAOLINA_LIBRARY_DIR}")

  # ask PAOLINA-config for the include dir
  #EXEC_PROGRAM( ${PAOLINA_CONFIG}
  #  ARGS "--include" 
  #  OUTPUT_VARIABLE PAOLINA_headers )
  #SET(PAOLINA_INCLUDE_DIR ${PAOLINA_headers})

  # set INCLUDE_DIRS to prefix+include
      EXEC_PROGRAM(${PAOLINA_CONFIG}
        ARGS --prefix
        OUTPUT_VARIABLE PAOLINA_PREFIX)
      SET(PAOLINA_INCLUDE_DIR ${PAOLINA_PREFIX}/include CACHE STRING INTERNAL)


  MESSAGE("DBG PAOLINA_INCLUDE_DIR ${PAOLINA_INCLUDE_DIR}")
      
  # ask PAOLINA-config for the library varaibles
  EXEC_PROGRAM( ${PAOLINA_CONFIG}
    ARGS "--libs" 
    OUTPUT_VARIABLE paolina_flags )

  SET(PAOLINA_LIBRARIES ${paolina_flags})

  MESSAGE("DBG PAOLINA_LIBRARIES ${PAOLINA_LIBRARIES}")

  # Set PAOLINA_INCLUDES
  SET( PAOLINA_INCLUDES ${PAOLINA_INCLUDE_DIR})

  MESSAGE("DBG PAOLINA_INCLUDES ${PAOLINA_INCLUDES}")

  SET(LD_LIBRARY_PATH ${LD_LIBRARY_PATH} ${PAOLINA_LIBRARY_DIR})

  MESSAGE("LD_LIBRARY_PATH ${LD_LIBRARY_PATH}")

  
    ELSE(PAOLINA_CONFIG)
      MESSAGE("FindPAOLINA.cmake: PAOLINA-config not found. Please set it manually. PAOLINA_CONFIG=${PAOLINA_CONFIG}")
    ENDIF(PAOLINA_CONFIG)

IF(PAOLINA_LIBRARIES)
  IF(PAOLINA_INCLUDE_DIR OR PAOLINA_CXX_FLAGS)

    SET(PAOLINA_FOUND 1)
    
  ENDIF(PAOLINA_INCLUDE_DIR OR PAOLINA_CXX_FLAGS)
ENDIF(PAOLINA_LIBRARIES)

